package claude

import (
	"os"
	"path/filepath"
	"strings"

	"github.com/agentepics/epics.sh/internal/hostapi"
)

type Adapter struct{}

func (Adapter) Name() string {
	return "claude"
}

func (Adapter) InstallDir(cwd, slug string) string {
	return filepath.Join(cwd, ".claude", "skills", slug)
}

func (Adapter) Setup(cwd string) (hostapi.Result, error) {
	files := map[string]string{
		filepath.Join(".claude", "commands", "epics-resume.md"): resumeCommand(),
		filepath.Join(".claude", "commands", "epics-info.md"):   infoCommand(),
		filepath.Join(".claude", "commands", "epics-doctor.md"): doctorCommand(),
		filepath.Join(".epics", "hosts", "claude", "README.md"): readme(),
	}

	var result hostapi.Result
	for relative, content := range files {
		changed, err := writeIfMissingOrSame(filepath.Join(cwd, relative), content)
		if err != nil {
			return hostapi.Result{}, err
		}
		if changed {
			result.Created = append(result.Created, filepath.ToSlash(relative))
		} else {
			result.Unchanged = append(result.Unchanged, filepath.ToSlash(relative))
		}
	}

	claudeMDPath := filepath.Join(cwd, "CLAUDE.md")
	created, err := writeIfMissingOrSame(claudeMDPath, claudeMD())
	if err != nil {
		return hostapi.Result{}, err
	}
	if created {
		result.Created = append(result.Created, "CLAUDE.md")
	} else {
		result.Unchanged = append(result.Unchanged, "CLAUDE.md")
	}

	return result, nil
}

func writeIfMissingOrSame(path, content string) (bool, error) {
	if raw, err := os.ReadFile(path); err == nil {
		if strings.TrimSpace(string(raw)) == strings.TrimSpace(content) {
			return false, nil
		}
		return false, nil
	}

	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return false, err
	}
	if err := os.WriteFile(path, []byte(strings.TrimSpace(content)+"\n"), 0o644); err != nil {
		return false, err
	}
	return true, nil
}

func claudeMD() string {
	return "# CLAUDE.md\n\n" +
		"This workspace uses the `epics` CLI as the canonical Epic control surface.\n\n" +
		"Use these Claude slash commands when they are available:\n\n" +
		"- `/epics-resume` to reconstruct the current workflow context\n" +
		"- `/epics-info` to inspect the installed Epic package\n" +
		"- `/epics-doctor` to diagnose workspace and adapter setup\n\n" +
		"Keep Epic semantics in the package files and use Claude-specific files only as wrappers around the CLI."
}

func resumeCommand() string {
	return "Run `epics resume` in the repository root. Use the returned context to continue the current Epic without re-deriving state from scratch."
}

func infoCommand() string {
	return "Run `epics info` in the repository root. Summarize the active Epic package, source, and installed metadata before proceeding."
}

func doctorCommand() string {
	return "Run `epics doctor` in the repository root. Report any failing or warning checks before continuing with adapter-sensitive work."
}

func readme() string {
	return "# Claude Host Setup\n\n" +
		"This directory is generated by `epics host setup claude`.\n\n" +
		"Files created in V1:\n\n" +
		"- installed Epic packages under `.claude/skills/<slug>/`\n" +
		"- Claude slash-command prompts under `.claude/commands/`\n" +
		"- a minimal workspace `CLAUDE.md` when one did not already exist\n\n" +
		"The setup is intentionally additive and avoids overwriting existing Claude workspace files."
}
